# Site settings
theme: minima
title: Rollz Vancouver
description: Vancouver's premium rolled ice cream destination, crafted fresh with premium ingredients.
author: Rollz Team
email: info@rollzyvr.com
url: https://rollzyvr.com/ # Replace with your GitHub Pages URL
baseurl: "" # Set to "/repository-name" if hosted in a subdirectory

# Social media
social:
  instagram: https://www.instagram.com/rollzvancouver/
  # twitter: https://twitter.com/rollzvancouver # Add if applicable
  # facebook: https://www.facebook.com/rollzicecreams # Add if applicable

# Navigation
header_pages:
  - qr/menu/menu.md
  - locations.md
  - about.md
  - contact.md

# Minima theme settings
minima:
  skin: classic # Options: classic, dark, solarized, solarized-dark
  social_links:
    instagram: rollzicecreams
    # Add other platforms as needed
  date_format: "%b %-d, %Y"

# SEO and plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  
minima:
  custom_css:
    - /assets/css/custom.css